# build: genera _site
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# runtime: copia html, css, js, assets, fonts, posts
FROM nginx:alpine

COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/_site /usr/share/nginx/html

EXPOSE 80